sonar.projectKey=jsaldana-idrobo_tpaga-datafono-challenge
sonar.organization=jsaldana-idrobo-key
sonar.host.url=https://sonarcloud.io

sonar.projectName=tpaga-datafono-challenge
sonar.sourceEncoding=UTF-8

sonar.sources=App.tsx,index.js,src,android/app/src/main/java
sonar.tests=__tests__,e2e,android/app/src/test
sonar.test.inclusions=__tests__/**/*.test.ts,__tests__/**/*.test.tsx,e2e/**/*.e2e.ts,android/app/src/test/**/*.kt

sonar.typescript.tsconfigPath=tsconfig.json
sonar.javascript.lcov.reportPaths=coverage/lcov.info

sonar.exclusions=**/node_modules/**,**/coverage/**,**/.scannerwork/**,**/android/**/build/**,**/ios/Pods/**
sonar.coverage.exclusions=index.js,android/**,ios/**,e2e/**,__tests__/**,__mocks__/**,jest.setup.ts,src/navigation/navigationTypes.ts,**/*.styles.ts
sonar.cpd.exclusions=**/*.styles.ts
